platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Stone' do

pod 'AFNetworking', '3.1.0', :inhibit_warnings => true

pod 'CocoaAsyncSocket'

pod 'Masonry'

pod 'SDWebImage'

pod 'JSPatch', :inhibit_warnings => true

pod 'Aspects'

pod 'BlocksKit'

end
